### ISSUE TITLE
Amun jump of the Plane

### ISSUE THREAD

**Issue by christophergalli** [DigiBP/Team-Habsburg-Castle#1]
Amun has to order a flight from Zürich to Lucern, and open the door while flight and jump into the engine.

**Comment by christophergalli** [comment]
Are you serious to jump into the engine?

**Comment by christophergalli** [comment]
ok I understood, I will take care of this...

**Comment by AmunStalder** [comment]
I will jump only if you come with me

**Comment by christophergalli** [comment]
yes but on the other sideeeeeeeee

**Comment by christophergalli** [comment]
Hey @AmunStalder you need to check if there is a door on the other sideeeee
